"""Added firstname lastname and email columns to Users

Revision ID: 19e2c2d2b891
Revises: 4b73fb7216d9
Create Date: 2024-06-08 01:49:25.294656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e2c2d2b891'
down_revision: Union[str, None] = '4b73fb7216d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('lastname', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Users', 'email')
    op.drop_column('Users', 'lastname')
    op.drop_column('Users', 'firstname')
    # ### end Alembic commands ###
